###  request with disabled redirects
# @no-redirect
POST http://lara-pro.loc/api/categories/
Content-Type: application/json

{
    "name": "history"
}


###

###  request with disabled redirects
# @no-redirect
POST http://lara-pro.loc/api/categories/
Content-Type: application/json

{
    "name": "fiction"
}
###
###
# @no-redirect
POST http://lara-pro.loc/api/categories/
Content-Type: application/json

{
    "name": "fantasy2"
}


###
### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###

### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}


###


### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###


### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###



### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###


### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###


### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###


### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###


### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###


### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###


### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###


### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###

### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###

### Send POST request with json body

POST http://lara-pro.loc/api/books/
Content-Type: application/json

{
    "name": "Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "en",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": "{{$random.integer(1,3)}}"
}

###
