### Send PUT request with dynamic variables in request's body

### Send PUT request with json body

PUT http://lara-pro.loc/api/books/{{$random.integer(1,10)}}
Content-Type: application/json

{
    "name": "Updated Book {{$random.alphabetic(5)}} {{$randomInt}}",
    "year": {{$random.integer(1970,2023)}},
    "lang": "ua",
    "pages": "{{$random.integer(1, 55000)}}",
    "categoryId": {{$random.integer(1, 3)}}
}

###

#{
# "categoryId": {{$random.integer(1, 3)}}
#
# $languages = ['en', 'ua', 'pl', 'de'];
#    "login": "{{$random.alphabetic(10)}}",
#    "password": "{{$random.alphanumeric(8)}}",
#    "email": "{{$random.email}}",
#    "score": "{{$random.float(-10.2, 12.3)}}",
#    "id": "{{$random.uuid}}",
#    "attachment": "{{$random.hexadecimal(30)}}",
#    "phone_number": "+{{$random.integer(100)}} ({{$random.integer(100, 999)}}) {{$random.integer(100, 999)}} {{$random.integer(10, 99)}}-{{$random.integer(10, 99)}}",
#    "timestamp": "{{$isoTimestamp}}"
#}
